### ISSUE TITLE
get Invalid wave header found 

### ISSUE THREAD

**Issue by MahmoudMabrok** [Tarteel-io/Tarteel-ML#23] opened 2019-03-08 08:32 UTC
I have  cloned Tarteel-ML repo, started to download csv for Alfatiha as mentioned in wiki but i got error 
all i do was 
 ```
python3 download.py -s 1
Downloading CSV from https://d2sf46268wowyo.cloudfront.net/datasets/tarteel_v1.0.csv
Done downloading CSV.
Invalid wave header found .audio/s1/a4/1_4_2787081723.wav , removing.
Invalid wave header found .audio/s1/a3/recording_FO94M2V.wav , removing.
Invalid wave header found .audio/s1/a1/1_1_3752224010.wav , removing.
Invalid wave header found .audio/s1/a6/1_6_4035742518.wav , removing.
Invalid wave header found .audio/s1/a2/1_2_4115400297.wav , removing.
Audio file .audio/s1/a5/1_5_4027410949.wav does not have speech according to VAD. Removing.
Audio file .audio/s1/a7/1_7_456658554.wav does not have speech according to VAD. Removing.
Invalid wave header found .audio/s1/a2/1_2_2198883921.wav , removing.
Invalid wave header found .audio/s1/a6/1_6_3964846100.wav , removing.
Audio file .audio/s1/a4/1_4_3355668251.wav does not have speech according to VAD. Removing.
Invalid wave header found .audio/s1/a1/1_1_526190118.wav , removing.
Invalid wave header found .audio/s1/a6/1_6_4081852003.wav , removing.
Invalid wave header found .audio/s1/a6/1_6_1540864270.wav , removing.
Audio file .audio/s1/a1/1_1_1740606045.wav does not have speech according to VAD. Removing.
Invalid wave header found .audio/s1/a3/1_3_1486618514.wav , removing.
Invalid wave header found .audio/s1/a5/1_5_1812842962.wav , removing.
Invalid wave header found .audio/s1/a2/1_2_2615458200.wav , removing.
Invalid wave header found .audio/s1/a3/1_3_2791353353.wav , removing.
Invalid wave header found .audio/s1/a3/1_3_619438520.wav , removing.
Audio file .audio/s1/a4/1_4_3452859238_pbxN174.wav does not have speech according to VAD. Removing.
Invalid wave header found .audio/s1/a7/1_7_3771589469.wav , removing.
Invalid wave header found .audio/s1/a6/1_6_1220528519.wav , removing.
Audio file .audio/s1/a3/1_3_409467092_jRelUpO.wav does not have speech according to VAD. Removing.

```

python 3.7.1 
linux ubuntu 16.04

**Comment by piraka9011** [comment] 2019-03-11 15:13
Looks like its related to the issue described in the Tarteel-api repo. Have you tried anything to debug/solve the issue? There are header issues probably caused by uploading different audio formats from different devices.

**Comment by khanh111** [comment] 2019-09-07 12:40
Resolved by the recent refactor of download.py in 21d8e54772ca54468f182c28c4cb743aec21a751.

**Closed** 2019-09-07 12:41 UTC
